appCardVendor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # home page 
    path('', views.index, name='index'),
    # Vendor Views
    path('vendors', views.VendorListView.as_view(), name='vendor_list'),
    path('vendor/create', views.VendorCreateView.as_view(), name='vendor_create_form'),
    path('vendor/<int:pk>/update', views.VendorUpdateView.as_view(), name='vendor_update_form'),
    path('vendor/<int:pk>/delete', views.VendorDeleteView.as_view(), name='vendor_confirm_delete'),
    path('load_card_data', views.load_card_data, name='load_card_data'), 
    # Card Views
    path('cards', views.CardListView.as_view(), name='card_list'),
    path('card/create', views.CardCreateView.as_view(), name='card_create_form'),
    path('card/<int:pk>/update', views.CardUpdateView.as_view(), name='card_update_form'),
    path('card/<int:pk>/delete', views.CardDeleteView.as_view(), name='card_confirm_delete'),
]

ccapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appCardVendor/', include('appCardVendor.urls')),
    path('', RedirectView.as_view(url='/appCardVendor/')),
]


    

appCardVendor/models.py
from django.db import models
from datetime import date
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Vendor(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    card = models.ForeignKey('Card', on_delete=models.SET_NULL, null=True) # set null to True so if card is deleted then vendor is NOT deleted.
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('vendor_update_form', args=[str(self.id)])
    
class Card(models.Model):
    TYPE_CHOICES = (
        ('American Express', 'American Express'),
        ('Mastercard', 'Mastercard'),
        ('Visa', 'Visa'),
    )
    nickname = models.CharField(max_length=50)
    name_on_card = models.CharField(max_length=50)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default="American Express")
    card_number = models.CharField(max_length=16, validators=[RegexValidator(r'^\d{1,16}$', message='Card number has to be 16 digits, no spaces')])
    security_code = models.CharField(max_length=4, validators=[RegexValidator(r'^\d{1,4}$', message='Security code has to be 3 or 4 digits, no spaces')])
    expiry_date = models.DateField()
    
    
    def __str__(self):
        return self.nickname
        
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('card_update_form', args=[str(self.id)])
    

appCardVendor/forms.py
from django import forms
from datetime import date
from django.forms import widgets
from django.forms import SelectDateWidget

from .models import Vendor, Card

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = '__all__'

        
class CardForm(forms.ModelForm):
    security_code = forms.CharField(
        min_length=3,
        max_length=4,
    )
    expiry_date = forms.DateField(
        widget=SelectDateWidget(),
    )
    class Meta:    
        model = Card
        fields = ['nickname', 'name_on_card', 'type', 'card_number', 'security_code', 'expiry_date']

appCardVendor/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Vendor, Card
from .forms import VendorForm, CardForm

# Create your views here.

def index(request):
    return render(request, 'appCardVendor/index.html')

class VendorListView(ListView):
    model=Vendor

class VendorCreateView(CreateView):
    model = Vendor
    form_class = VendorForm
    success_url = reverse_lazy('vendor_list')
    
    
class VendorUpdateView(UpdateView):
    model = Vendor
    form_class = VendorForm
    success_url = reverse_lazy('vendor_list')
    def get_context_data(self, **kwargs):
        context = super(VendorUpdateView, self).get_context_data(**kwargs)
        # get the card object corresponding to the vendor 
        context['card'] = self.object.card 
        return context

def load_card_data(request):
    card_id = request.GET.get('card')
    card = Card.objects.get(pk=card_id)
    return render(request, 'appCardVendor/load_card_data.html', {'card': card})
    
class VendorDeleteView(DeleteView):
    model = Vendor
    success_url = reverse_lazy('vendor_list')

class CardListView(ListView):
    model=Card

class CardCreateView(CreateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('card_list')
        
class CardUpdateView(UpdateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('card_list')

class CardDeleteView(DeleteView):
    model = Card
    success_url = reverse_lazy('card_list')
        

    

appCardVendor/templates/appCardVendor/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>AutoPay Tracker</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>

<body>

   {% block navbar %} 
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a href="{% url 'index'%}" class="navbar-brand  text-success">AutoPay Tracker</a>
    </nav>
    
    {% endblock %}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2 list-group list-group-flush">
              {% block sidebar %}
                  <a class="list-group-item list-group-item-action" href="{% url 'index' %}">Home</a></li>
                  <a class="list-group-item list-group-item-action" href="{% url 'vendor_list' %}">Payees</a></li>
                  <a class="list-group-item list-group-item-action" href="{% url 'card_list'%}">Credit Cards</a></li>
              {% endblock %}
          </div>
          <div class="col-sm-10 ">
            <div class="mx-auto block-content">
                {% block content %}{% endblock %}
            </div>
          </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>  
</body>
</html>

appCardVendor/templates/appCardVendor/card_confirm_delete.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}

<h1>Delete Card</h1>

<p>Are you sure you want to delete <strong>{{ card }}</strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>

</form>

{% endblock %}

appCardVendor/templates/appCardVendor/card_create_form.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}
<h1>Add a Credit Card</h1>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

appCardVendor/templates/appCardVendor/card_form.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}
<h1>Credit Card</h1>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <button type="submit" class="btn btn-success">Submit</button>
     <a class="btn btn-secondary" href="{% url 'card_list' %}">Cancel</a>
</form>

{% endblock %}

appCardVendor/templates/appCardVendor/card_list.html
{% extends "appCardVendor/base_generic.html" %}
{% block content %}
<div class="mb-3">
<h1>Credit Cards</h1>
</div>
{% if card_list %}
    {% for card in card_list %}
        <dl class="row">
            <dt class="col-sm-6">
                <a class="text-muted" href="{% url 'card_update_form' card.id %}">{{ card.nickname }}</a>
            </dt>
            <dt class="col-sm-1">
                <a class="btn btn-light" href="{% url 'card_update_form' card.id %}">Edit</a>
            </dt>
            <dt class="col-sm-1">
                <a class="btn btn-light" href="{% url 'card_confirm_delete' card.id %}">Delete</a>
            </dt>
        </dl>   
    {% endfor %}  
{% else %}
    <p>There are no credit cards registered to your account.</p>
{% endif %} 
<a class="btn btn-success" href="{% url 'card_create_form' %}" role="button">Add a Credit Card</a>
{% endblock %}        

appCardVendor/templates/appCardVendor/index.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}

<div>
        <h1 class="display-4">AutoPay Tracker</h1>
        <p class="lead">Track your recurring bill payments (subscriptions, utility bills, instalments) and quickly update the payment information when necessary - for example, when you receive a new credit card in the mail.</p>
        <a class="btn btn-lg btn-success" href="{% url 'vendor_create_form' %}" role="button" >Add a Payee</a>
        <a class="btn btn-lg btn-success" href="{% url 'card_create_form' %}"  role="button" >Add a Credit Card</a>
</div>

{% endblock %}

appCardVendor/templates/appCardVendor/load_card_data.html
<!-- <p>{{ card.card_number}} {{ card.expiry_date}}</p> -->

<!-- 
<table>
    <tr>
        <th>Card Number:</th>
        <td>{{ card.card_number}}</td>
    </tr>
    <tr>
        <th>Expiry Date:</th>
        <td>{{ card.expiry_date}}</td>
    </tr>
</table>
-->
<table>
    <tr>
        <th><label for="card_number">Card Number:</label></th>
        <td><input type="text" name="card_data" id="card_number" placeholder="{{card.card_number}}" disabled></td>
    </tr>
    <tr>
        <th><label for="expiry_date">Expiry Date:</label></th>
        <td><input type="text" name="card_data" id="expiry_date" placeholder="{{card.expiry_date}}" disabled></td>
    </tr>
</table>

appCardVendor/templates/appCardVendor/vendor_confirm_delete.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}

<h1>Delete Payee</h1>

<p>Are you sure you want to delete <strong>{{ vendor }}</strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
  
  <button type="submit" class="btn btn-danger">Yes, Delete</button>
</form>

{% endblock %}

appCardVendor/templates/appCardVendor/vendor_form.html
{% extends "appCardVendor/base_generic.html" %}

{% block content %}
<h1>Payee</h1>
<form method="post" id="vendorForm" data-card-url="{% url 'load_card_data' %}">
    {% csrf_token %}
    <table>
        {{ form }}</br>
        
    </table>
    <div id="ajax_card_data">
        <table>
            <tr>
                <th><label for="card_number">Card Number:</label></th>
                <td><input type="text" name="card_data" id="card_number" placeholder="{{card.card_number}}" disabled></td>
            </tr>
            <tr>
                <th><label for="expiry_date">Expiry Date:</label></th>
                <td><input type="text" name="card_data" id="expiry_date" placeholder="{{card.expiry_date}}" disabled></td>
            </tr>
        </table>
    </div>
    <!-- <input type="submit" value="Submit" /> -->
    <button type="submit" class="btn btn-success">Submit</button>
    <a class="btn btn-secondary" href="{% url 'vendor_list' %}">Cancel</a>
    
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_card").change(function () { 
        var url = $("#vendorForm").attr("data-card-url");
        var card_id = $(this).val();
        console.log(card_id)
        $.ajax({
            url: url,
            data: {
                'card': card_id
            },
            success: function (data) {
                $('#ajax_card_data').html(data);
            }
        });
    });
</script>
  
{% endblock %}

appCardVendor/templates/appCardVendor/vendor_list.html
{% extends "appCardVendor/base_generic.html" %}
{% block content %}
<div class="mb-3">
    <h1>Payees</h1>
</div>
{% if vendor_list %}
    {% for vendor in vendor_list %}
        <dl class="row">
            <dt class="col-sm-6">
                <a class="text-muted" href="{% url 'vendor_update_form' vendor.id %}">{{ vendor.name }}</a>
            </dt>
            <dt class="col-sm-1">
                <a class="btn btn-light" href="{% url 'vendor_update_form' vendor.id %}">Edit</a>
            </dt>
            <dt class="col-sm-1">
                <a class="btn btn-light" href="{% url 'vendor_confirm_delete' vendor.id %}">Delete</a>
            </dt>
        </dl>   
    {% endfor %}          
{% else %}
    <p>There are no payees registered your account.</p>
{% endif %} 
<a class="btn btn-success" href="{% url 'vendor_create_form' %}" role="button">Add a Payee</a>
{% endblock %}             